### ISSUE TITLE
Group related issues

### ISSUE THREAD

**Issue by adithyaappu** [KlausSchaefers/quant-ux#202]
## ! Work in progress

From #182 List 2

- [ ] 31. Selecting a group within a group is not possible.
- [ ] 32. Cloning a grouped item changes the layer order. #200 
- [ ] 33. Selecting multiple objects inside a group. Currently, there is no way to do that.
- [ ] 34. For a group W and H adjustment is not available.
- [ ] Groups should have rezize #178 
- [ ] 35. Right now, adding the effects for a group is not possible.
- [ ] 36. Aligning a group with another object is not possible. Aligning a Group with another Object is not possible. #184

**Comment by KlausSchaefers** [comment]
Hi,

I have updated the selection handling quite a lot. Now you can "click" the select down to sub groups. Also subgroups can be moved. What do you think?
